### PR TITLE
Dev randy

### PR DESCRIPTION
**Pull request by randyjap**
- Publishing checks
- Initial UI for publishing (will make more modifications later)
- Label required fields required

### CODE REVIEW

**Comment by jensjap** [comment]
I believe we need to add a breadcrumb to return to the index page after someone navigates to show/edit

**Comment by jensjap** [comment]
so breadcrumb should read:
my projects > sr360 items > preview sr360
my projects > sr360 items > edit sr360

**Comment by jensjap** [comment]
I just realized this change has nothing to do with this PR. I should have caught it sooner. Let me know if you want to include the change in this PR or make a new one. Either way is fine.

**Comment by randyjap** [comment]
@jensjap added the bread crumbs
@bisen now returns 400 status with empty body with bad request

**Pull request merged**
