### PR TITLE
Feature containerization

### PR DESCRIPTION
**Pull request by sleepwalk712**
Run the following command after you run docker compose up in the first time: 
docker-compose exec app bundle exec rails db:setup db:schema:load  RAILS_ENV=development

I was trying to use non-root user, but many gems you used in the project needs root privilege. So this version we use root in Dockerfile.

### CODE REVIEW

**Comment by jensjap** [comment]
Looks good. I think since we are setting this up for development, we can go ahead and add port 3000 docker-entrypoint.sh.
Give me some time to fix our seed data. I don't think it is correctly set up for a clean environment before I'll merge this into master.

**Comment by jensjap** [comment]
I don't think we should check-in .env file. It will overwrite existing .env file on deployment servers.

**Comment by sleepwalk712** [comment]
I renamed .env and related file

**Review by jensjap — APPROVED** [review]

**Comment by jensjap** [comment]
Updated, squashed and merged into docker branch.

**Pull request closed without merging**
