### PR TITLE
Change fhir project status

### PR DESCRIPTION
**Pull request by sleepwalk712**

### CODE REVIEW

**Review by jensjap — CHANGES_REQUESTED** [review]
A publishing existing for a project sets up a request for publishing. We need to check whether the publishing has an approval.

**Comment by sleepwalk712** [comment]
> A publishing existing for a project sets up a request for publishing. We need to check whether the publishing has an approval.

So do we check is approvable_type equals to "Publishing"?

**Comment by jensjap** [comment]
@sleepwalk712 
If we check from the direction of the publishing then we only need to check for the existence of the approval. The approval must have approvable_type: "Publishing" because the parent of the approval is of type "Publishing".

An example where we do this can be see on app/views/shared/_topbar_nav.html.erb:289
sd_meta_datum.publishing.approval.present?
In this example the approval will have an approvable_type of "SdMetaDatum" but we don't have to check for it because we are navigating through the parent.

So in this case I would do the following with using safe navigation operator:
project&.publishing&.approval.present?

**Review by jensjap — APPROVED** [review]
This is also okay.

**Pull request merged**
